name: Develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy develop branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lektor
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run python lint
        run: lektor deploy develop