name: Develop CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy develop branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lektor
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Install plugins
        run: lektor plugins reinstall
      - name: Build site
        run: lektor build
      - name: Lektor deploy
        if: github.event_name == 'push'
        env:
          LEKTOR_DEPLOY_USERNAME: ${{ secrets.LEKTOR_DEPLOY_USERNAME }}
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.LEKTOR_DEPLOY_PASSWORD }}
        run: lektor deploy develop