name: Production CI

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy production branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: production
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/lektor/builds
          key: ${{ runner.os }}-py-production-cache
          restore-keys: ${{ runner.os }}-py-production-cache
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lektor
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Install plugins
        run: lektor plugins reinstall
      - name: Build site
        run: lektor build
      - name: Lektor deploy
        if: github.event == 'push'
        env:
          LEKTOR_DEPLOY_USERNAME: ${{ secrets.LEKTOR_DEPLOY_USERNAME }}
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.LEKTOR_DEPLOY_PASSWORD }}
        run: lektor deploy production